### ISSUE TITLE
configure mutations & actions

### ISSUE THREAD

**Issue by waltherneto** [waltherneto/real-world-vue2#20]
in order to enhance data storage manipulation on this project

**Comment by waltherneto** [comment]
### Tasks
- [ ] install new dependency
- [ ] flesh out our **EventCard** component
- [ ] add a **mutation & action** to our Vuex Store
- [ ] route to our newly created event
